### PR TITLE
Update the version of desktop and put repetitive version string into …

### PR DESCRIPTION
**Pull request by Jikstra**
…a variable

### CODE REVIEW

**Comment by ghost** [comment]
The download links throw 404 errors. While the folder indeed has the `v` in the beginning, the filenames of the downloads don't use the `v` in the version number.

**Comment by Jikstra** [comment]
I changed the upload script running on the bbmac to drop the v and ruploaded the 0.999.1 release, so it should now work.

**Comment by Jikstra** [comment]
I would like to have it consistent, so trying to fix it on the electron builder side.

**Comment by ghost** [comment]
The links all work: https://staging.delta.chat/280/en/download

And portable is visible now as well.

**Pull request merged**
