### PR TITLE
Revert "Build website with nix"

### LINKED ISSUE #898: Built pages for staging.delta.chat have an incorrect modification date
As noticed in https://github.com/deltachat/sysadmin/issues/167, pages built by our CI for staging.delta.chat have a modification date of 1970-01-01. To me it looks like this was introduced together when [switching the build to nix](https://github.com/deltachat/deltachat-pages/commit/0d1937ee9e46732a6dee433282ddb554a3ae7552).

### PR DESCRIPTION
**Pull request by missytake**
Let's see if this fixes #898.

### CODE REVIEW

**Review by hpk42 — APPROVED** [review]
Works although the securejoin did not work and the echo bot sent back an undecrsptable message but afterwards it worked.

**Comment by link2xt** [comment]
> Works although the securejoin did not work and the echo bot sent back an undecrsptable message but afterwards it worked.

How echobot is related to deltachat-pages?

**Comment by link2xt** [comment]
If 0 unix timestamp is a problem, better use `-I` (`--ignore-times`) flag on rsync, no need to revert the whole PR.

**Comment by missytake** [comment]
> If 0 unix timestamp is a problem, better use `-I` (`--ignore-times`) flag on rsync, no need to revert the whole PR.

Doesn't help, and leaving out -t doesn't help either. The timestamp is still set to `1970-01-01`.

In general I think using nix for this is not a good idea, as only half of the responsible people can debug nix builds locally. Or why did we introduce it? It worked before, no? https://github.com/deltachat/deltachat-pages/pull/819 doesn't point to a bug which was fixed by it, it only mentions that it makes sure that developers use the same jekyll version as the CI, but as some of us still don't use nix this doesn't really hold.

**Comment by missytake** [comment]
I'll merge this for now as it fixes the issue, we can later revert it and fix it differently if we want to keep using nix.

**Comment by link2xt** [comment]
> The timestamp is still set to 1970-01-01.

Is this timestamp needed for anything?

**Comment by hagenest** [comment]
> > The timestamp is still set to 1970-01-01.
> 
> Is this timestamp needed for anything?

currently we use it for deleting old builds on staging, see https://github.com/deltachat/sysadmin/issues/167.

**Comment by link2xt** [comment]
> Doesn't help, and leaving out -t doesn't help either. The timestamp is still set to 1970-01-01.

I just tested with https://github.com/deltachat/deltachat-pages/pull/903, here is the result:
```
$ ls -lah /var/www/html/staging/903/
total 260K
dr-xr-xr-x 23 jekyll jekyll 4.0K Jun  3 10:28 .
drwxr-xr-x 21 jekyll jekyll  215 Jun  3 10:28 ..
dr-xr-xr-x  2 jekyll jekyll   62 Jun  3 10:28 .well-known
-r--r--r--  1 jekyll jekyll 1.4K Jun  3 10:28 35c3.html
-r--r--r--  1 jekyll jekyll 1.6K Jun  3 10:28 36c3.html
-r--r--r--  1 jekyll jekyll 6.7K Jun  3 10:28 37c3.html
-r--r--r--  1 jekyll jekyll  727 Jun  3 10:28 404.html
-r--r--r--  1 jekyll jekyll  35K Jun  3 10:28 LICENSE
-r--r--r--  1 jekyll jekyll 7.2K Jun  3 10:28 README.md
dr-xr-xr-x 11 jekyll jekyll  170 Jun  3 10:28 assets
dr-xr-xr-x  2 jekyll jekyll  336 Jun  3 10:28 ca
dr-xr-xr-x  2 jekyll jekyll  336 Jun  3 10:28 cs
dr-xr-xr-x  2 jekyll jekyll  336 Jun  3 10:28 de
dr-xr-xr-x  2 jekyll jekyll 8.0K Jun  3 10:28 en
dr-xr-xr-x  2 jekyll jekyll  336 Jun  3 10:28 es
-r--r--r--  1 jekyll jekyll  15K Jun  3 10:28 favicon.ico
-r--r--r--  1 jekyll jekyll 120K Jun  3 10:28 feed.xml
-r--r--r--  1 jekyll jekyll 1.5K Jun  3 10:28 flake.lock
-r--r--r--  1 jekyll jekyll  947 Jun  3 10:28 flake.nix
dr-xr-xr-x  2 jekyll jekyll  336 Jun  3 10:28 fr
dr-xr-xr-x  2 jekyll jekyll  336 Jun  3 10:28 gl
-r--r--r--  1 jekyll jekyll   53 Jun  3 10:28 google1730128c2b186138.html
-r--r--r--  1 jekyll jekyll   53 Jun  3 10:28 google2faa16b6e4ce3d8b.html
dr-xr-xr-x  2 jekyll jekyll  336 Jun  3 10:28 id
dr-xr-xr-x  2 jekyll jekyll  336 Jun  3 10:28 it
dr-xr-xr-x  2 jekyll jekyll  336 Jun  3 10:28 nl
dr-xr-xr-x  2 jekyll jekyll  336 Jun  3 10:28 pl
dr-xr-xr-x  2 jekyll jekyll  336 Jun  3 10:28 pt
dr-xr-xr-x  2 jekyll jekyll  336 Jun  3 10:28 pt_BR
-r--r--r--  1 jekyll jekyll   26 Jun  3 10:28 robots.txt
dr-xr-xr-x  2 jekyll jekyll  336 Jun  3 10:28 ru
-r--r--r--  1 jekyll jekyll  23K Jun  3 10:28 sitemap.xml
dr-xr-xr-x  2 jekyll jekyll  336 Jun  3 10:28 sk
dr-xr-xr-x  2 jekyll jekyll  336 Jun  3 10:28 sq
dr-xr-xr-x  2 jekyll jekyll  336 Jun  3 10:28 tr
dr-xr-xr-x  2 jekyll jekyll  336 Jun  3 10:28 uk
dr-xr-xr-x  2 jekyll jekyll  336 Jun  3 10:28 zh_CN
```

Leaving out `-t` results in applying new timestamp to copied files and `-I` should work to overwrite files regardless of timestamp for non-preview.

**Pull request merged**
