### PR TITLE
added video calls to FAQ

### PR DESCRIPTION
**Pull request by ghost**
Not sure if we should already put this in the FAQ - it is still an experimental feature, after all.

### CODE REVIEW

**Comment by Simon-Laux** [comment]
what about instruction on the other platforms?

**Comment by ghost** [comment]
I included Android - is the process the same on iOS?

**Comment by r10s** [comment]
> Not sure if we should already put this in the FAQ - it is still an experimental feature, after all.

i'd say no.

maybe better put that to the howto-section in the forum for now?

the thing is still experimental, i assume, we would get more issues reported if we push ppl in the faq to it, eg. why "cannot i start calls in groups". i think, user expectations are far lower when it is flagged as "experimental" and user are not pushed to it.

there are some plans to streamline things after the next release (email compat), so maybe better wait until then.

also, ios does not have the feature yet, and if we add it there, it will probably go to the "paper clip" and can be used as an attachment (maybe that would be a nicer approach for android as well, it is in the main menu only because it was the simplest way to do iirc)

**Comment by r10s** [comment]
k, closing this for now.

**Pull request closed without merging**
