### PR TITLE
Bots post images css

### PR DESCRIPTION
**Pull request by ghost**
An alternative way to order & format the pictures in the blogpost.

### CODE REVIEW

**Comment by pabzm** [comment]
I don't care too much about where to place the pictures. But I'd like to keep the order, because in the first picture the light is shining on the bot-figurine — there's a meaning in there :)

**Comment by pabzm** [comment]
(Actually I think the page looks cleaner with the pictures underneath each other, but you appear to strongly disagree, otherwise you wouldn't have done the work of a new PR. And against strong opinions on this, I'd rather withdraw.)

**Comment by ghost** [comment]
Great ;) yeah, my opinion is somewhat strong.

**Comment by ghost** [comment]
I changed the order back, merge?

**Review by pabzm — APPROVED** [review]
Looks good to me!

**Pull request merged**
