### PR TITLE
update translations

### PR DESCRIPTION
**Pull request by r10s**
ran `./tools/t-dance.sh pull`

### CODE REVIEW

**Comment by gerryfrancis** [comment]
WIP, not finished, yet, please do not merge atm, thanks!

**Comment by gerryfrancis** [comment]
@r10s You can repull from Transifex now, thanks! :)

**Comment by r10s** [comment]
did so, the preview should be updated in some minutes.

**Comment by gerryfrancis** [comment]
@r10s Please repull again, I did some minor but important grammar correction, so sorry ... thanks again!

**Pull request merged**
