### PR TITLE
Fall back to English translation

### LINKED ISSUE #238: menus broken on some languages
eg. https://delta.chat/ca/ displays the footer as `| |` the translations for "Imprint" etc. are missing.

and for https://delta.chat/fr/ the download (!) link in the header is gone:

Screen Shot 2020-01-08 at 22 21 23

### PR DESCRIPTION
**Pull request by Simon-Laux**
this could be way nicer code if liquid supported functions

fixes #238

### CODE REVIEW

**Review by r10s — APPROVED** [review]
if this works, we should merge it (ci is not yet ready). at some point, we can re-think the approach.

**Review by ghost — APPROVED** [review]
works: https://staging.delta.chat/242/ca/

**Comment by Simon-Laux** [comment]
The right way would to make and use an jekyll plugin in ruby for this. https://jekyllrb.com/docs/plugins/
maybe @pabzm knows how it is done. I believe his ruby skills are way higher than mine (mine are nonexistent)

**Comment by pabzm** [comment]
I could write a jekyll plugin, yes. But if it works currently, I'd rather spend my time with other things. If it becomes a problem again, please hit me up then.

**Pull request merged**
