### PR TITLE
add Brazilian Portuguese

### PR DESCRIPTION
**Pull request by r10s**
this was missing, although significantly translated meanwhile

### CODE REVIEW

**Review by missytake — APPROVED** [review]
There is still a lot untranslated, but probably actually publishing the translations encourages translators :) And it's still helpful I guess

**Comment by missytake** [comment]
I prepared the change for the language redirect, will report here as soon as it works.

**Comment by missytake** [comment]
language redirect seems to work, test case exists :)

**Comment by r10s** [comment]
cool, thanks a lot!

**Pull request merged**
