### PR TITLE
New blog post: Shining some light on bots

### PR DESCRIPTION
**Pull request by pabzm**
A short blog post to let people know about bots.delta.chat and the forum category.

### CODE REVIEW

**Comment by pabzm** [comment]
(Jo and Lotta built the pictured bots.)

**Comment by ghost** [comment]
Cool pictures :)

I would format them slightly differently, which is not an easy topic to discuss of course; I opened an alternative PR: https://github.com/deltachat/deltachat-pages/pull/331

Feel free to merge it if you like the approach or ignore it if you don't. I like the blogpost as it is, I think we can publish this.

**Review by ghost — APPROVED** [review]

**Review by adbenitez — APPROVED** [review]
nice

**Comment by pabzm** [comment]
Merging with 2 approvals.

**Pull request merged**
