### PR TITLE
update russian translation

### PR DESCRIPTION
**Pull request by r10s**

### CODE REVIEW

**Comment by r10s** [comment]
@link2xt maybe you can have rough look - or was the translation done even by you? :)

**Comment by link2xt** [comment]
Improved it a bit on transifex, update once more

**Comment by r10s** [comment]
> Improved it a bit on transifex, update once more

thanks a lot, i do

**Comment by guland2000** [comment]
@r10s
Russian language full update!
It was easy but i done with it.
Please update Russian site for nice good looking :-)

**Comment by r10s** [comment]
thanks a lot, i pulled the translations, there should be a preview at https://github.com/deltachat/deltachat-pages/pull/911 soon

**Pull request merged**
