### PR TITLE
Move to Libera.Chat

### PR DESCRIPTION
**Pull request by Hocuri**

### CODE REVIEW

**Comment by Hocuri** [comment]
The link  https://kiwiirc.com/nextclient/#irc://irc.libera.chat/deltachat doesn't work, but I couldn't find out why :/

**Comment by link2xt** [comment]
Replace with https://kiwiirc.com/nextclient/#ircs://irc.libera.chat/deltachat

**Review by missytake — APPROVED** [review]
That link works for me.

**Comment by link2xt** [comment]
I grepped over the repo. There is also a mention of freenode in the README: "Ping r10s or compl4xx on irc.freenode.net/#deltachat". Probably ok for now. Other mentions are in translations and published blog posts, they don't need any change.

**Review by flub — APPROVED** [review]

**Comment by flub** [comment]
let's update the readme as well though, otherwise is confusing

**Comment by r10s** [comment]
i think, we can just strike the whole "Ping r10s or compl4xx ..." sentence. ppl writing a blog post will know that - and we will also notice a new post and act as needed.

**Comment by Hocuri** [comment]
@r10s Done.

FTR, I approve merging this PR, too (I can't hit "approve" as it's my own PR)

**Pull request merged**
