### PR TITLE
Russian version of website

### PR DESCRIPTION
**Pull request by netzoom**
I looked that there is no website's section on Russian language. I'm just trying to help with it.

### CODE REVIEW

**Comment by netzoom** [comment]
Done. #35

**Comment by r10s** [comment]
Thank you very much, I've just merged it.

@Ampli-fier I hope that this was okay for you, if not, please let me know and I stop editing the homepage until your pending changes are commited.

**Comment by Ampli-fier** [comment]
Fine, I'll manage :) Cool to have another Language!

**Comment by r10s** [comment]
:)

**Pull request merged**
