### PR TITLE
some formatting and typo issues in the english gdpr text

### PR DESCRIPTION
**Pull request by hpk42**

### CODE REVIEW

**Comment by r10s** [comment]
lgtm, did you also noticed #81 ?

**Comment by hpk42** [comment]
nope, didn't see that before ... will cause conflicts one way or the other :/

**Comment by r10s** [comment]
`en/gdpr.md` only includes `_includes/gdpr-international.md` , so i think this pr should be closed and a new based upon gdpr-international should be created.

sorry for the confusion

**Comment by hpk42** [comment]
need to redo the pr afte rthe others were merged.

**Pull request closed without merging**
