### PR TITLE
remove incomplete norwegian translation

### PR DESCRIPTION
**Pull request by ghost**
Norwegian is only 3% translated - we can't really say we offer a norwegian translation. Until this improves, let's take it out.

### CODE REVIEW

**Comment by r10s** [comment]
how is the automatic language selection working? does it need adaption? but also asking because of interest :)

**Review by r10s — COMMENTED** [review]
lgtm, unsure about the automatic language selection, though :)

**Comment by ghost** [comment]
I need to adjust it on the server, but only testable after it's merged, I guess.

**Comment by ghost** [comment]
done: https://github.com/deltachat/sysadmin/tree/master/delta.chat#removing-norwegian-translation-from-delta-chat

**Comment by r10s** [comment]
thanks for the link!

**Comment by hpk42** [comment]
great log!

**Pull request merged**
