### PR TITLE
Add RELEASES.md, fill in android releases

### PR DESCRIPTION
**Pull request by Hocuri**

### CODE REVIEW

**Comment by r10s** [comment]
there is already https://github.com/deltachat/deltachat-pages/blob/main/releases.md - i think, the idea was to have it all at one glance?

**Comment by Hocuri** [comment]
I didn't know about this, will move it. Yes, the idea was to have it at a glance.

**Review by r10s — APPROVED** [review]
lgtm, the main usefulness will at the end come from the file being updated (the easier format and the less effort, the better)

there is also amazon, huawei and this site - but no need to add that to this PR

**Comment by ralphtheninja** [comment]
`git rm RELEASES.md`?

**Comment by Hocuri** [comment]
Thanks for catching, fixed: https://github.com/deltachat/deltachat-pages/pull/973

**Pull request merged**
