### PR TITLE
update translations

### PR DESCRIPTION
**Pull request by r10s**

### CODE REVIEW

**Review by missytake — APPROVED** [review]
I checked the links, looks fine.

The anchor äinks (#encryption) are brekaing - is this intended? It *llooks* like nothing would fail.

**Comment by r10s** [comment]
> The anchor äinks (#encryption) are brekaing - is this intended? It llooks like nothing would fail.

the anchor was removed at https://github.com/deltachat/deltachat-pages/pull/564/files#diff-d4c3e5414f550d84ffce94a04386b7a390beaad75539782e303085bcd914d9b3L201 - and therefore also in all translations.

not sure, if it is used somewhere, however, if there is some dangling link somewhere, one would still land atop of the page, so maybe good enough.

**Comment by missytake** [comment]
On the staging page it works, I think `_includes/toc.html` creates the anchor links, not markdown. So it doesn't affect anything. It's just a bit weird that the toc.html code is already there since 2019 and those anchor links only get removed now. But whatever.

Anything in the way of merging?

**Comment by r10s** [comment]
> Anything in the way of merging?

no :)

**Pull request merged**
