### PR TITLE
added css+html for blog preview featured images

### LINKED ISSUE #265: Show first image of a blog post on delta.chat/blog
Right now, delta.chat/blog shows the title and the first paragraph of a blogpost, together with a "Read on..." link to the actual blogpost:

Screenshot_2020-01-20_16-18-14

It would be really cool if we could show the featured image on this page as well, i.e. the first image of the post.

This was first brought up in #226 :)

### PR DESCRIPTION
**Pull request by ghost**
closes #265 

the css crops the featured images so they look good in the preview both on desktop & mobile.

The formats for featured images for future blogposts are atm something like 320x178 (mobile preview) + 275x200 (desktop preview), but mobile is a bit dynamic.

### CODE REVIEW

**Comment by ghost** [comment]
This looks already quite good.

Only some of the older posts which have neither a long excerpt nor a featured-image at all look a bit deplaced. I'd adjust them so they have longer excerpts and images? finding appropriate screenshots shouldn't be hard in most cases.

**Comment by pabzm** [comment]
Nice! Maybe you could link the images to the blog-post, too?

**Comment by r10s** [comment]
looks great! so much better :) 
for others: direct link: https://staging.delta.chat/282/en/blog

nitpicking: there are pretty large gaps now between posts _without_ images, esp. the older ones. not a big deal and should not block merging, but if it is simple to fix, maybe we can do that.

**Review by Simon-Laux — APPROVED** [review]

**Comment by ghost** [comment]
> looks great! so much better :)
> for others: direct link: https://staging.delta.chat/282/en/blog
> 
> nitpicking: there are pretty large gaps now between posts _without_ images, esp. the older ones. not a big deal and should not block merging, but if it is simple to fix, maybe we can do that.

Easier than I thought. finding new featured images would have been nicer, but this looks good, too ;)

Ready to merge?

**Review by pabzm — APPROVED** [review]
Looks much nicer than before, thanks!

**Pull request merged**
