### PR TITLE
link to pinned tweet about leaving twitter

### PR DESCRIPTION
**Pull request by hpk42**

### CODE REVIEW

**Review by r10s — APPROVED** [review]
nice!

**Comment by link2xt** [comment]
Follow-up: #591

**Comment by rosano** [comment]
I understand the sentiment to shit on Twitter as it burns or make a political stance by favoring other mediums, but wouldn't stop posting there or hide it or leave it.

**Comment by r10s** [comment]
this pr is only about removing the twitter advertisement from our page - and i do not think, that this will harm much as ppl are already on delta.chat.

we also do not have advertisements for facebook, instagram and whatnot - twitter was an exception for $reasons, but these reasons fade away these days.

if or if not we continue posting on twitter from time to time, is another thing - afaik, there is not much traffic from twitter anyway.

also, we need someone who cares for twitter - if there is no one left in the team, this is an issue on its own :)

**Comment by hpk42** [comment]
> I understand the sentiment to shit on Twitter as it burns or make a political stance by favoring other mediums, but wouldn't stop posting there or hide it or leave it.

@rosano I am open to re-discussing this sometime but the "leaving twitter" has been building up for a longer time. We left twitter already in the last couple of months -- several posts were fediverse only.  We also have a "notifications chat" where five people are following/answering fediverse interactions.

**Pull request merged**
