### PR TITLE
Reapply "Build website with nix"

### PR DESCRIPTION
**Pull request by link2xt**

### CODE REVIEW

**Review by missytake — APPROVED** [review]
Looks good. I think we can close #902 as well with this?

**Review by hagenest — APPROVED** [review]
still bullish about nix, although I'm not 100% what it does better in this specific case :D

**Comment by link2xt** [comment]
#902 is a bit independent, I can use nix instead but the issue is that readme tells you to install jekyll but then does not actually use installed jekyll because bundler installs another copy.

**Comment by link2xt** [comment]
> still bullish about nix, although I'm not 100% what it does better in this specific case :D

I don't really care if nix is used by CI, but want to be able to run `nix build` to get a website copy locally.

**Pull request merged**
