### PR TITLE
incorporated feedback from group and forum qr code howto

### PR DESCRIPTION
**Pull request by Yettte**

### CODE REVIEW

**Review by r10s — APPROVED** [review]
review is mainly about replaced asset.

i also did a quick side-by-side comparison of old and new pdf, however, not in detail - i assume, this is was already discussed in background channels :)

**Comment by hpk42** [comment]
Screenshot from 2022-01-12 12-27-39
looks good apart from this minor detail in the screenshot where the sentence starts somewhere inside the graphic and it's "how" instead of "now".  This is not a show stopper so approving anyway (you can merge yourself now i think but could also fix this little issue and merge then, your choice).

**Review by hpk42 — APPROVED** [review]

**Comment by Yettte** [comment]
I corrected the sentence, thanks for the feedback.

**Comment by Yettte** [comment]
it's fixed, thanks for the feedback!

**Pull request closed without merging**
