### PR TITLE
Update German translation

### PR DESCRIPTION
**Pull request by lukkigi**
Should fix issue #183

### CODE REVIEW

**Comment by r10s** [comment]
thanks!

when we merge this pr, we should not forget to do a `tx push -t -l de` afterwards - otherwise the changes will be overwritten by the next pull from transifex.

in general, we should overthink this whole handling of the localized website, it seems to be too complicated ... but this is another issue ;)

**Comment by ghost** [comment]
@r10s on which machine do we need to do that push? Locally, and commit this? or on the machine? now, after the migration...

**Comment by r10s** [comment]
> Locally, and commit this?

yip, there is no special machine involved, the logic is mainly in ./tools/t-dance - we take the english .md file, convet it to a po file, push that to transifex

when things are translatated, we pull the translations as .po files, convert that to .md files, that is pushed then.

**Comment by r10s** [comment]
if we want to keep the international pages, it would be cool if that can be automated, eg. every change on /en could be pushed as .po files to transifex

**Comment by Simon-Laux** [comment]
I believe this is outdated now

**Pull request closed without merging**
