### PR TITLE
add links to the stores and upgrade the download version to 1.4.x

### PR DESCRIPTION
**Pull request by Simon-Laux**
should we only merge this after we have the updated versions in the stores?
Update: I'll upload the store versions this evening, and it takes days before its in the store anyway so I'll merge this now.

### CODE REVIEW

**Comment by r10s** [comment]
great! /o/  \o\  /o/ ... \o/

**Comment by Simon-Laux** [comment]
though now there is the question how we can make the two options more distinct as its not apparent that it is a file download on the non-appstore button.

**Comment by r10s** [comment]
maybe just use the textual buttons as for linux, having one apple and ios logo should be recognizale enough.

text could be "Get Setup.exe for Windows" and "Get .DMG for macOS"  or so.

btw, is the "you also need to install Microsoft's Visual C++ Redistributable" hint still required?

**Comment by Simon-Laux** [comment]
> maybe just use the textual buttons

that's also what I thought of.

> text could be "Get Setup.exe for Windows" and "Get .DMG for macOS" or so.

we could probably even leave the platform/OS out of there, because its in a box labeled like the platform and next to the button with the logo?

> btw, is the "you also need to install Microsoft's Visual C++ Redistributable" hint still required?

no, but it still can't hurt... but we should weaken it instead, like if it doesn't work try installing vcredist. or sth along those lines?

**Pull request merged**
