### PR TITLE
add some users voices

### PR DESCRIPTION
**Pull request by r10s**

### CODE REVIEW

**Comment by Simon-Laux** [comment]
desktop isn't very accessible for blind people so I'm not sure whether we should include that quote right now.
https://github.com/deltachat/deltachat-desktop/issues/1791

**Review by Simon-Laux — APPROVED** [review]
LGTM

**Review by ghost — APPROVED** [review]

**Comment by r10s** [comment]
> desktop isn't very accessible for blind people so I'm not sure whether we should include that quote right now.
> [deltachat/deltachat-desktop#1791](https://github.com/deltachat/deltachat-desktop/issues/1791)

the source-line says "about the Android version", so i'd say this is fine (iOS version is also accessible afaik)

**Comment by hpk42** [comment]
good start!

however, the user stories/voices link appears a bit unmotivated at the end of the front page. 

also two quick "user voice" tweet links FYI: 

https://twitter.com/gozala/status/1281346020664729600

https://twitter.com/skadge/status/1276515066393878529

**Comment by r10s** [comment]
> however, the user stories/voices link appears a bit unmotivated at the end of the front page.

thats true. i first added the voices directly on the homepage, however that appears not so nice, too much text on the start page. but we can probably make the link a bit nicer and/or frame it by a small headline or so. i'll add a commit, i will also incorporate the two links you provided - thanks!

**Pull request merged**
